# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Server configuration module for Calamares
# Allows configuring SSH/VNC plus ROCm AI server products.
# SSH/VNC are shown only when included by netinstall.
# Voice AI is shown only when its optional ROCm package was selected.
# DS4, XDNA SDK import, Synapse Dub, and TRELLIS.2 are shown only for Strix Halo profiles.
# Private AMD SDK and Xilinx license import happens only after explicit EULA acceptance;
# proprietary artifacts remain outside the ISO and pacman repository.
# Synapse Dub package selection, licenses, specialist translation, and Wan VACE backend belong to this page.
#
# QML search mode: "both", "qrc", "branding"
qmlSearch: both

# Sidebar / progress label
qmlLabel:
    server: "Server Setup"
    server[it]: "Configurazione Server"
