/* === This file is part of Calamares - <https://calamares.io> ===
 *
 *   SPDX-FileCopyrightText: 2026 Mario Giustiniani <mariogiustiniani@gmail.com>
 *   SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Server configuration module.
 *
 * Visibility rules:
 * - SSH is shown only when openssh is included by netinstall.
 * - VNC is shown only when wayvnc or x11vnc is included by netinstall.
 * - Voice AI is shown only when its optional ROCm package was selected.
 * - Synapse Dub, DS4, and TRELLIS.2 are shown only for Strix Halo ROCm profiles.
 *
 * The Server tab is the product surface for ROCm-backed AI/server products.
 */

import io.calamares.core 1.0
import io.calamares.ui 1.0

import QtQuick 2.7
import QtQuick.Controls 2.2
import QtQuick.Window 2.2
import QtQuick.Layouts 1.3
import QtQuick.Controls.Material 2.1

Item {
    id: root
    width: 740
    height: 420

    property var selectedPackages: Global.value("netinstallPackages") || []
    property var aiSelection: Global.value("packagechooser_ai") || ""

    function containsPackage(pkg) {
        return selectedPackages && selectedPackages.indexOf(pkg) !== -1
    }

    function isStrixHaloProfile(id) {
        return id === "Strix Halo platform generics" ||
               id === "Bosgame M5" ||
               id === "ROG Flow Z13-KJP"
    }

    property bool hasSshd: containsPackage("openssh")
    property bool hasVnc:  containsPackage("wayvnc") || containsPackage("x11vnc")

    // Strix Halo can be detected either from the AI profile id or from the
    // netinstall package set generated by that profile.
    property bool hasStrixHalo: isStrixHaloProfile(aiSelection) ||
                                containsPackage("synapse-strixhalo-config") ||
                                containsPackage("rocm-hip-sdk")

    property bool hasDs4: hasStrixHalo
    property bool hasXdna: hasStrixHalo && containsPackage("synapse-xdna-runtime")
    property bool hasWhisperXdna: hasStrixHalo && containsPackage("synapse-whisper-xdna")
    property bool hasWhisperX: containsPackage("synapse-whisperx-rocm")
    property bool hasComfyUI: containsPackage("synapse-comfyui-rocm")
    property bool hasCvml: containsPackage("synapse-cvml-runtime")
    property bool hasVoice: containsPackage("synapse-voice-ai-rocm")
    property bool hasDub: hasStrixHalo
    property bool hasTrellis: hasStrixHalo

    function saveConfig() {
        var config = {
            "ssh_enabled": hasSshd ? sshEnabled.checked : false,
            "ssh_port": sshPort.value,
            "ssh_auth": sshAuth.currentIndex,
            "vnc_enabled": hasVnc ? vncEnabled.checked : false,
            "vnc_port": vncPort.value,
            "vnc_password": vncPassword.text,
            "llm_enabled": hasDs4 && llmEnabled.checked ? "true" : "false",
            "llm_model": llmModel.currentIndex,
            "llm_mode": llmMode.currentIndex,
            "llm_port": llmPort.value,
            "xdna_import_enabled": hasXdna && xdnaImportEnabled.checked ? "true" : "false",
            "xdna_eula_accepted": hasXdna && xdnaEulaAccepted.checked ? "true" : "false",
            "xdna_runtime_source": xdnaRuntimeSource.text,
            "xdna_license_source": xdnaLicenseSource.text,
            "xdna_runtime_root": xdnaRuntimeRoot.text,
            "voice_enabled": hasVoice ? voiceEnabled.checked : false,
            "voice_model_source": voiceModelSource.text,
            "voice_model_mode": voiceModelMode.currentIndex,
            "voice_model_root": voiceModelRoot.text,
            "voice_llm_endpoint": voiceLlmEndpoint.text,
            "voice_bind_mode": voiceBindMode.currentIndex,
            "voice_port": voicePort.value,
            "voice_language": voiceLanguage.currentText,
            "voice_asr_backend": voiceAsrBackend.currentIndex,
            "whisperx_enabled": hasWhisperX ? "true" : "false",
            "whisperx_model_mode": whisperxModelMode.currentIndex,
            "whisperx_model_root": whisperxModelRoot.text,
            "whisperx_language": whisperxLanguage.currentText,
            "whisperx_all_languages": whisperxAllLanguages.checked ? "true" : "false",
            "whisperx_diarization": whisperxDiarization.checked ? "true" : "false",
            "whisperx_diarization_terms": whisperxDiarizationTerms.checked ? "true" : "false",
            "whisperx_hf_token": whisperxHfToken.text,
            "comfyui_enabled": hasComfyUI ? "true" : "false",
            "comfyui_model_root": comfyuiModelRoot.text,
            "comfyui_model_mode": comfyuiModelMode.currentIndex,
            "comfyui_bind_mode": comfyuiBindMode.currentIndex,
            "comfyui_port": comfyuiPort.value,
            "cvml_enabled": hasCvml ? "true" : "false",
            "cvml_eula_accepted": cvmlEulaAccepted.checked ? "true" : "false",
            "cvml_source": cvmlSource.text,
            "cvml_target": cvmlTarget.text,
            "dub_enabled": hasDub ? dubEnabled.checked : false,
            "dub_license_accepted": hasDub ? dubLicenseAccepted.checked : false,
            "dub_model_mode": dubModelMode.currentIndex,
            "dub_asr_backend": dubAsrBackend.currentIndex,
            "dub_model_root": dubModelRoot.text,
            "dub_translation_endpoint": dubTranslationEndpoint.text,
            "dub_translation_model": dubTranslationModel.text,
            "translation_enabled": hasDub && dubEnabled.checked ? translationEnabled.checked : false,
            "translation_license_accepted": translationLicenseAccepted.checked,
            "translation_model_mode": translationModelMode.currentIndex,
            "translation_model_source": translationModelSource.text,
            "translation_model_root": translationModelRoot.text,
            "translation_bind_mode": translationBindMode.currentIndex,
            "translation_port": translationPort.value,
            "generative_enabled": hasDub && dubEnabled.checked ? generativeEnabled.checked : false,
            "generative_model_mode": generativeModelMode.currentIndex,
            "generative_model_root": generativeModelRoot.text,
            "trellis_enabled": hasTrellis ? trellisEnabled.checked : false,
            "trellis_download_models": trellisDownloadModels.checked,
            "trellis_model_root": trellisModelRoot.text,
            "trellis_pipeline_type": trellisPipelineType.currentText
        }
        Global.insert("server_config", config)
    }

    function onLeave() {
        saveConfig()
    }

    Component.onDestruction: saveConfig()

    Flickable {
        id: flick
        anchors.fill: parent
        contentHeight: 3350

        ScrollBar.vertical: ScrollBar {
            id: fscrollbar
            width: 10
            policy: ScrollBar.AlwaysOn
        }

        ColumnLayout {
            x: 1
            y: 0
            width: parent.width - fscrollbar.width
            spacing: 16

            Label {
                Layout.fillWidth: true
                wrapMode: Text.WordWrap
                text: "Server products. SSH/VNC follow netinstall package selection; ROCm AI products are available with Strix Halo profiles."
            }

            // ── SSH Section ───────────────────────────────────
            GroupBox {
                title: "SSH"
                Layout.fillWidth: true
                visible: hasSshd

                ColumnLayout {
                    spacing: 8

                    CheckBox {
                        id: sshEnabled
                        text: "Enable SSH server"
                        checked: true
                    }

                    Label { text: "SSH Port:" }
                    SpinBox {
                        id: sshPort
                        from: 1024
                        to: 65535
                        value: 22
                        enabled: sshEnabled.checked
                    }

                    Label { text: "Authentication:" }
                    ComboBox {
                        id: sshAuth
                        model: ["Password only", "Key + Password", "Key only"]
                        enabled: sshEnabled.checked
                    }
                }
            }

            // ── VNC Section ───────────────────────────────────
            GroupBox {
                title: "VNC"
                Layout.fillWidth: true
                visible: hasVnc

                ColumnLayout {
                    spacing: 8

                    CheckBox {
                        id: vncEnabled
                        text: "Enable VNC server"
                        checked: false
                    }

                    Label { text: "VNC Port:" }
                    SpinBox {
                        id: vncPort
                        from: 5900
                        to: 5999
                        value: 5901
                        enabled: vncEnabled.checked
                    }

                    Label { text: "Password:" }
                    TextField {
                        id: vncPassword
                        echoMode: TextInput.Password
                        placeholderText: "VNC password"
                        enabled: vncEnabled.checked
                    }
                }
            }

            // ── DS4 Section ───────────────────────────────────
            GroupBox {
                title: "AI / ROCm — DS4"
                Layout.fillWidth: true
                visible: hasDs4

                ColumnLayout {
                    spacing: 8

                    CheckBox {
                        id: llmEnabled
                        text: "Install and enable DS4 inference server"
                        checked: false
                    }

                    Label { text: "Model quant:" }
                    ComboBox {
                        id: llmModel
                        model: ["q2-imatrix (81 GB)", "q2-q4-imatrix (98 GB)", "q4-imatrix (153 GB)"]
                        enabled: llmEnabled.checked
                    }

                    Label { text: "Mode:" }
                    ComboBox {
                        id: llmMode
                        model: ["Local (127.0.0.1)", "Remote (0.0.0.0)"]
                        enabled: llmEnabled.checked
                    }

                    Label { text: "API Port:" }
                    SpinBox {
                        id: llmPort
                        from: 1024
                        to: 65535
                        value: 8000
                        enabled: llmEnabled.checked
                    }
                }
            }

            // ── XDNA2 / Ryzen AI SDK Section ─────────────────
            GroupBox {
                title: "AI / NPU — AMD Ryzen AI Software"
                Layout.fillWidth: true
                visible: hasXdna

                ColumnLayout {
                    spacing: 8

                    Label {
                        Layout.fillWidth: true
                        wrapMode: Text.WordWrap
                        text: "Optional post-install import from a private USB drive. The AMD SDK archive and Xilinx license are never included in the Synapse ISO or pacman repository."
                    }

                    CheckBox {
                        id: xdnaEulaAccepted
                        text: "I accept the AMD Ryzen AI 1.7.1 and third-party EULAs"
                        checked: false
                        onCheckedChanged: if (!checked) xdnaImportEnabled.checked = false
                    }

                    Label {
                        Layout.fillWidth: true
                        wrapMode: Text.WordWrap
                        text: "AMD EULA: https://account.amd.com/content/dam/account/en/licenses/download/amd-end-user-license-agreement.pdf\nThird-party notices: https://account.amd.com/content/dam/account/en/licenses/download/ryzen-ai-1.7.1-linux-tpn-license.pdf"
                    }

                    CheckBox {
                        id: xdnaImportEnabled
                        text: "Find the private USB automatically and install the XDNA ONNX runtime"
                        checked: false
                        enabled: xdnaEulaAccepted.checked
                    }

                    Label { text: "Ryzen AI SDK source:" }
                    TextField {
                        id: xdnaRuntimeSource
                        text: "auto"
                        placeholderText: "auto or path to ryzen_ai-1.7.1.tgz / model_source.tar.gz"
                        enabled: xdnaImportEnabled.checked
                        Layout.fillWidth: true
                    }

                    Label { text: "Xilinx license source:" }
                    TextField {
                        id: xdnaLicenseSource
                        text: "auto"
                        placeholderText: "auto or path to Xilinx.lic"
                        enabled: xdnaImportEnabled.checked
                        Layout.fillWidth: true
                    }

                    Label { text: "Installed runtime root:" }
                    TextField {
                        id: xdnaRuntimeRoot
                        text: "/opt/synapse/xdna/ryzen-ai/1.7.1"
                        enabled: xdnaImportEnabled.checked
                        Layout.fillWidth: true
                    }
                }
            }

            // ── Voice AI Section ──────────────────────────────
            GroupBox {
                title: "AI / Audio — Voice Studio"
                Layout.fillWidth: true
                visible: hasVoice

                ColumnLayout {
                    spacing: 8

                    CheckBox {
                        id: voiceEnabled
                        text: "Configure local Voice AI services"
                        checked: true
                    }

                    Label { text: "Model archive source:" }
                    TextField {
                        id: voiceModelSource
                        text: "auto"
                        placeholderText: "auto or /path/to/models"
                        enabled: voiceEnabled.checked
                        Layout.fillWidth: true
                    }

                    Label { text: "Model acquisition:" }
                    ComboBox {
                        id: voiceModelMode
                        model: ["Use external model archive", "Download from Internet"]
                        enabled: voiceEnabled.checked
                    }

                    Label { text: "Installed model root:" }
                    TextField {
                        id: voiceModelRoot
                        text: "/var/lib/synapse/voice-ai/models"
                        enabled: voiceEnabled.checked && voiceModelMode.currentIndex === 1
                        Layout.fillWidth: true
                    }

                    Label { text: "LLM endpoint:" }
                    TextField {
                        id: voiceLlmEndpoint
                        text: "http://192.168.5.157:8000/v1"
                        enabled: voiceEnabled.checked
                        Layout.fillWidth: true
                    }

                    Label { text: "Default language:" }
                    ComboBox {
                        id: voiceLanguage
                        model: ["it", "en", "fr", "de", "es", "pt"]
                        enabled: voiceEnabled.checked
                    }

                    Label {
                        text: "Speech recognition backend:"
                        visible: hasXdna
                    }
                    ComboBox {
                        id: voiceAsrBackend
                        model: [
                            "ROCm GPU (default)",
                            "XDNA NPU with ROCm/CPU fallback",
                            "CPU"
                        ]
                        enabled: voiceEnabled.checked
                        visible: hasXdna
                    }

                    Label { text: "API exposure:" }
                    ComboBox {
                        id: voiceBindMode
                        model: ["Local (127.0.0.1)", "Remote (0.0.0.0)"]
                        enabled: voiceEnabled.checked
                    }

                    Label { text: "Voice API port:" }
                    SpinBox {
                        id: voicePort
                        from: 1024
                        to: 65535
                        value: 8090
                        enabled: voiceEnabled.checked
                    }

                    Label {
                        Layout.fillWidth: true
                        wrapMode: Text.WordWrap
                        text: "Voice samples are enrolled after first login and remain private in the user's local data directory."
                    }
                }
            }

            // ── ComfyUI ROCm Section ──────────────────────────
            GroupBox {
                title: "AI / Visual — ComfyUI ROCm"
                Layout.fillWidth: true
                visible: hasComfyUI
                ColumnLayout {
                    spacing: 8
                    Label { text: "External model root:" }
                    TextField { id: comfyuiModelRoot; text: "/var/lib/synapse/comfyui/models"; Layout.fillWidth: true }
                    Label { text: "Z-Image Turbo acquisition:" }
                    ComboBox {
                        id: comfyuiModelMode
                        model: [
                            "Automatic: models USB, then Internet",
                            "Download from Internet",
                            "Use models USB in place",
                            "Runtime only — acquire later"
                        ]
                    }
                    Label { text: "Network access:" }
                    ComboBox { id: comfyuiBindMode; model: ["Localhost only", "Local network"] }
                    Label { text: "ComfyUI port:" }
                    SpinBox { id: comfyuiPort; from: 1024; to: 65535; value: 8188 }
                    Label {
                        Layout.fillWidth: true
                        wrapMode: Text.WordWrap
                        text: "ComfyUI diffusion runs on Radeon ROCm. Models remain external and community custom nodes are not installed automatically."
                    }
                }
            }

            // ── AMD CVML Section ───────────────────────────────
            GroupBox {
                title: "AI / Vision — AMD Ryzen AI CVML"
                Layout.fillWidth: true
                visible: hasCvml
                ColumnLayout {
                    spacing: 8
                    Label {
                        Layout.fillWidth: true
                        wrapMode: Text.WordWrap
                        textFormat: Text.RichText
                        text: "Review the <a href='https://github.com/amd/RyzenAI-SW/blob/main/Ryzen-AI-CVML-Library/LICENSE.txt'>AMD CVML SDK license</a>. CVML is imported after installation and is not included in the ISO."
                        onLinkActivated: function(link) { Qt.openUrlExternally(link) }
                    }
                    CheckBox { id: cvmlEulaAccepted; text: "I accept the AMD CVML SDK license"; checked: false }
                    Label { text: "CVML source (github or local ZIP/directory):" }
                    TextField { id: cvmlSource; text: "github"; Layout.fillWidth: true }
                    Label { text: "Private installation target:" }
                    TextField { id: cvmlTarget; text: "/opt/synapse/cvml/current"; Layout.fillWidth: true }
                    Label {
                        Layout.fillWidth: true
                        wrapMode: Text.WordWrap
                        text: "CVML can request the NPU explicitly for face detection, face mesh, and depth estimation. It is not a ComfyUI diffusion backend."
                    }
                }
            }

            // ── WhisperX post-processing Section ──────────────
            GroupBox {
                title: "AI / Audio — WhisperX post-processing"
                Layout.fillWidth: true
                visible: hasWhisperX

                ColumnLayout {
                    spacing: 8

                    Label { text: "Alignment model acquisition:" }
                    ComboBox {
                        id: whisperxModelMode
                        model: ["Download from Internet", "Use existing model directory"]
                    }

                    Label { text: "External model root:" }
                    TextField {
                        id: whisperxModelRoot
                        text: "/var/lib/synapse/whisperx/models"
                        Layout.fillWidth: true
                    }

                    Label { text: "Alignment language:" }
                    ComboBox {
                        id: whisperxLanguage
                        model: ["it", "en", "de", "es", "fr", "pt", "pl", "ru", "ja", "ko", "zh"]
                        enabled: !whisperxAllLanguages.checked
                    }
                    CheckBox {
                        id: whisperxAllLanguages
                        text: "Preserve all 11 alignment languages on external storage (about 15–30 GB)"
                        checked: false
                    }

                    Label {
                        Layout.fillWidth: true
                        wrapMode: Text.WordWrap
                        textFormat: Text.RichText
                        text: "Diarization model terms: <a href='https://huggingface.co/pyannote/speaker-diarization-community-1'>pyannote/speaker-diarization-community-1</a>"
                        onLinkActivated: function(link) { Qt.openUrlExternally(link) }
                    }
                    CheckBox {
                        id: whisperxDiarizationTerms
                        text: "I reviewed and accept the selected pyannote model terms"
                        checked: false
                        onCheckedChanged: if (!checked) whisperxDiarization.checked = false
                    }
                    CheckBox {
                        id: whisperxDiarization
                        text: "Download and enable optional speaker diarization"
                        checked: false
                        enabled: whisperxDiarizationTerms.checked
                    }

                    Label {
                        text: "Hugging Face token for gated diarization model (optional for alignment):"
                    }
                    TextField {
                        id: whisperxHfToken
                        echoMode: TextInput.Password
                        enabled: whisperxDiarization.checked
                        Layout.fillWidth: true
                    }

                    Label {
                        Layout.fillWidth: true
                        wrapMode: Text.WordWrap
                        text: "WhisperX runs word alignment and optional diarization on ROCm after XDNA Whisper transcription. Model weights remain external."
                    }
                }
            }

            // ── Synapse Dub Section ───────────────────────────
            GroupBox {
                title: "AI / ROCm — Custom Video Dubbing"
                Layout.fillWidth: true
                visible: hasDub

                ColumnLayout {
                    spacing: 8

                    CheckBox {
                        id: dubLicenseAccepted
                        text: "I accept the non-commercial XTTS-v2 and Wav2Lip model licenses"
                        checked: false
                        onCheckedChanged: if (!checked) dubEnabled.checked = false
                    }

                    Label {
                        Layout.fillWidth: true
                        wrapMode: Text.WordWrap
                        text: "Required licenses: https://coqui.ai/cpml.txt and the Wav2Lip non-commercial model terms."
                    }

                    CheckBox {
                        id: dubEnabled
                        text: "Install a complete and ready-to-use Synapse Dub pipeline"
                        checked: false
                        enabled: dubLicenseAccepted.checked
                    }

                    Label {
                        text: "Transcription backend:"
                        visible: hasWhisperXdna
                    }
                    ComboBox {
                        id: dubAsrBackend
                        model: ["OpenAI Whisper on ROCm (default)", "XDNA NPU with ROCm fallback"]
                        enabled: dubEnabled.checked
                        visible: hasWhisperXdna
                    }

                    Label { text: "Model acquisition:" }
                    ComboBox {
                        id: dubModelMode
                        model: ["Download from Internet", "Use existing model directory"]
                        enabled: dubEnabled.checked
                    }

                    Label { text: "Model root:" }
                    TextField {
                        id: dubModelRoot
                        text: "/var/lib/synapse/dub/models"
                        enabled: dubEnabled.checked
                        Layout.fillWidth: true
                    }

                    Label { text: "OpenAI-compatible dialogue/translation endpoint:" }
                    TextField {
                        id: dubTranslationEndpoint
                        text: "http://192.168.5.157:8000/v1"
                        enabled: dubEnabled.checked
                        Layout.fillWidth: true
                    }

                    Label { text: "Dialogue model:" }
                    TextField {
                        id: dubTranslationModel
                        text: "deepseek-v4-flash"
                        enabled: dubEnabled.checked
                        Layout.fillWidth: true
                    }

                    Label {
                        Layout.fillWidth: true
                        wrapMode: Text.WordWrap
                        text: "'synapse-dub custom' rewrites dialogue while preserving footage. Enable the generative backend below to create genuinely new visual scenes."
                    }

                    CheckBox {
                        id: translationLicenseAccepted
                        text: "I accept the SeamlessM4T-v2-large CC-BY-NC-4.0 model license"
                        checked: false
                        enabled: dubEnabled.checked
                        onCheckedChanged: if (!checked) translationEnabled.checked = false
                    }

                    Label {
                        Layout.fillWidth: true
                        wrapMode: Text.WordWrap
                        text: "SeamlessM4T-v2-large model license: https://creativecommons.org/licenses/by-nc/4.0/"
                    }

                    CheckBox {
                        id: translationEnabled
                        text: "Install the specialist SeamlessM4T ROCm translation server"
                        checked: false
                        enabled: dubEnabled.checked && translationLicenseAccepted.checked
                    }

                    Label { text: "Translation model acquisition:" }
                    ComboBox {
                        id: translationModelMode
                        model: ["Download from Internet", "Import existing model directory"]
                        enabled: translationEnabled.checked
                    }

                    Label { text: "Existing model source:"; visible: translationModelMode.currentIndex === 1 }
                    TextField {
                        id: translationModelSource
                        text: "/run/media/liveuser/models/models/safetensors/translation/seamless-m4t-v2-large"
                        visible: translationModelMode.currentIndex === 1
                        enabled: translationEnabled.checked
                        Layout.fillWidth: true
                    }

                    Label { text: "Installed translation model root:" }
                    TextField {
                        id: translationModelRoot
                        text: "/var/lib/synapse/translate/models/seamless-m4t-v2-large"
                        enabled: translationEnabled.checked
                        Layout.fillWidth: true
                    }

                    Label { text: "Translation server exposure:" }
                    ComboBox {
                        id: translationBindMode
                        model: ["Local (127.0.0.1)", "Remote (0.0.0.0)"]
                        enabled: translationEnabled.checked
                    }

                    Label { text: "Translation server port:" }
                    SpinBox {
                        id: translationPort
                        from: 1024
                        to: 65535
                        value: 8091
                        enabled: translationEnabled.checked
                    }

                    CheckBox {
                        id: generativeEnabled
                        text: "Install Wan2.1 VACE generative visual production (about 19 GB of models)"
                        checked: false
                        enabled: dubEnabled.checked
                    }

                    Label {
                        Layout.fillWidth: true
                        wrapMode: Text.WordWrap
                        text: "Wan2.1 VACE 1.3B and its Diffusers model are Apache-2.0 licensed. It creates new frames, scenes, actions, backgrounds, and camera motion from source reference frames."
                    }

                    Label { text: "Generative model acquisition:" }
                    ComboBox {
                        id: generativeModelMode
                        model: ["Download from Internet", "Use existing Wan VACE model directory"]
                        enabled: generativeEnabled.checked
                    }

                    Label { text: "Wan VACE model root:" }
                    TextField {
                        id: generativeModelRoot
                        text: "/var/lib/synapse/video-gen/models/wan-vace-1.3b"
                        enabled: generativeEnabled.checked
                        Layout.fillWidth: true
                    }
                }
            }

            // ── TRELLIS.2 Section ─────────────────────────────
            GroupBox {
                title: "AI / ROCm — TRELLIS.2"
                Layout.fillWidth: true
                visible: hasTrellis

                ColumnLayout {
                    spacing: 8

                    CheckBox {
                        id: trellisEnabled
                        text: "Install TRELLIS.2 ROCm image-to-3D"
                        checked: false
                    }

                    CheckBox {
                        id: trellisDownloadModels
                        text: "Download model weights during installation"
                        checked: true
                        enabled: trellisEnabled.checked
                    }

                    Label { text: "Model cache root:" }
                    TextField {
                        id: trellisModelRoot
                        text: "/var/lib/synapse/trellis2/models"
                        enabled: trellisEnabled.checked
                        Layout.fillWidth: true
                    }

                    Label { text: "Default quality profile:" }
                    ComboBox {
                        id: trellisPipelineType
                        model: ["512", "1024_cascade"]
                        enabled: trellisEnabled.checked
                    }

                    Label {
                        Layout.fillWidth: true
                        wrapMode: Text.WordWrap
                        text: "Model URLs remain editable in /etc/synapse/trellis2-rocm/models.conf for local mirrors or gated upstream models."
                    }
                }
            }
        }
    }
}
