/* === This file is part of Calamares - <https://calamares.io> ===
 *
 *   SPDX-FileCopyrightText: 2026 Mario Giustiniani <mariogiustiniani@gmail.com>
 *   SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Server configuration module.
 *
 * Visibility rules:
 * - SSH is shown only when openssh is included by netinstall.
 * - VNC is shown only when wayvnc or x11vnc is included by netinstall.
 * - Voice AI is shown only when its optional ROCm package was selected.
 * - DS4 and TRELLIS.2 are shown only when a Strix Halo AI profile was chosen.
 *
 * The Server tab is the product surface for ROCm-backed AI/server products.
 */

import io.calamares.ui 1.0

import QtQuick 2.7
import QtQuick.Controls 2.2
import QtQuick.Window 2.2
import QtQuick.Layouts 1.3
import QtQuick.Controls.Material 2.1

Item {
    id: root
    width: 740
    height: 420

    property var selectedPackages: configStorage.get("netinstallPackages") || []
    property var aiSelection: configStorage.get("packagechooser_ai") || ""

    function containsPackage(pkg) {
        return selectedPackages && selectedPackages.indexOf(pkg) !== -1
    }

    function isStrixHaloProfile(id) {
        return id === "Strix Halo platform generics" ||
               id === "Bosgame M5" ||
               id === "ROG Flow Z13-KJP"
    }

    property bool hasSshd: containsPackage("openssh")
    property bool hasVnc:  containsPackage("wayvnc") || containsPackage("x11vnc")

    // Strix Halo can be detected either from the AI profile id or from the
    // netinstall package set generated by that profile.
    property bool hasStrixHalo: isStrixHaloProfile(aiSelection) ||
                                containsPackage("synapse-strixhalo-config") ||
                                containsPackage("rocm-hip-sdk")

    property bool hasDs4: hasStrixHalo
    property bool hasVoice: containsPackage("synapse-voice-ai-rocm")
    property bool hasTrellis: hasStrixHalo

    function saveConfig() {
        var config = {
            "ssh_enabled": hasSshd ? sshEnabled.checked : false,
            "ssh_port": sshPort.value,
            "ssh_auth": sshAuth.currentIndex,
            "vnc_enabled": hasVnc ? vncEnabled.checked : false,
            "vnc_port": vncPort.value,
            "vnc_password": vncPassword.text,
            "llm_enabled": hasDs4 ? llmEnabled.checked : false,
            "llm_model": llmModel.currentIndex,
            "llm_mode": llmMode.currentIndex,
            "llm_port": llmPort.value,
            "voice_enabled": hasVoice ? voiceEnabled.checked : false,
            "voice_model_source": voiceModelSource.text,
            "voice_model_mode": voiceModelMode.currentIndex,
            "voice_model_root": voiceModelRoot.text,
            "voice_llm_endpoint": voiceLlmEndpoint.text,
            "voice_bind_mode": voiceBindMode.currentIndex,
            "voice_port": voicePort.value,
            "voice_language": voiceLanguage.currentText,
            "trellis_enabled": hasTrellis ? trellisEnabled.checked : false,
            "trellis_download_models": trellisDownloadModels.checked,
            "trellis_model_root": trellisModelRoot.text,
            "trellis_pipeline_type": trellisPipelineType.currentText
        }
        configStorage.set("server_config", config)
    }

    Component.onDestruction: saveConfig()

    Flickable {
        id: flick
        anchors.fill: parent
        contentHeight: 1550

        ScrollBar.vertical: ScrollBar {
            id: fscrollbar
            width: 10
            policy: ScrollBar.AlwaysOn
        }

        ColumnLayout {
            x: 1
            y: 0
            width: parent.width - fscrollbar.width
            spacing: 16

            Label {
                Layout.fillWidth: true
                wrapMode: Text.WordWrap
                text: "Server products. SSH/VNC follow netinstall package selection; ROCm AI products are available with Strix Halo profiles."
            }

            // ── SSH Section ───────────────────────────────────
            GroupBox {
                title: "SSH"
                Layout.fillWidth: true
                visible: hasSshd

                ColumnLayout {
                    spacing: 8

                    CheckBox {
                        id: sshEnabled
                        text: "Enable SSH server"
                        checked: true
                    }

                    Label { text: "SSH Port:" }
                    SpinBox {
                        id: sshPort
                        from: 1024
                        to: 65535
                        value: 22
                        enabled: sshEnabled.checked
                    }

                    Label { text: "Authentication:" }
                    ComboBox {
                        id: sshAuth
                        model: ["Password only", "Key + Password", "Key only"]
                        enabled: sshEnabled.checked
                    }
                }
            }

            // ── VNC Section ───────────────────────────────────
            GroupBox {
                title: "VNC"
                Layout.fillWidth: true
                visible: hasVnc

                ColumnLayout {
                    spacing: 8

                    CheckBox {
                        id: vncEnabled
                        text: "Enable VNC server"
                        checked: false
                    }

                    Label { text: "VNC Port:" }
                    SpinBox {
                        id: vncPort
                        from: 5900
                        to: 5999
                        value: 5901
                        enabled: vncEnabled.checked
                    }

                    Label { text: "Password:" }
                    TextField {
                        id: vncPassword
                        echoMode: TextInput.Password
                        placeholderText: "VNC password"
                        enabled: vncEnabled.checked
                    }
                }
            }

            // ── DS4 Section ───────────────────────────────────
            GroupBox {
                title: "AI / ROCm — DS4"
                Layout.fillWidth: true
                visible: hasDs4

                ColumnLayout {
                    spacing: 8

                    CheckBox {
                        id: llmEnabled
                        text: "Install and enable DS4 inference server"
                        checked: false
                    }

                    Label { text: "Model quant:" }
                    ComboBox {
                        id: llmModel
                        model: ["q2-imatrix (81 GB)", "q2-q4-imatrix (98 GB)", "q4-imatrix (153 GB)"]
                        enabled: llmEnabled.checked
                    }

                    Label { text: "Mode:" }
                    ComboBox {
                        id: llmMode
                        model: ["Local (127.0.0.1)", "Remote (0.0.0.0)"]
                        enabled: llmEnabled.checked
                    }

                    Label { text: "API Port:" }
                    SpinBox {
                        id: llmPort
                        from: 1024
                        to: 65535
                        value: 8000
                        enabled: llmEnabled.checked
                    }
                }
            }

            // ── Voice AI Section ──────────────────────────────
            GroupBox {
                title: "AI / Audio — Voice Studio"
                Layout.fillWidth: true
                visible: hasVoice

                ColumnLayout {
                    spacing: 8

                    CheckBox {
                        id: voiceEnabled
                        text: "Configure local Voice AI services"
                        checked: true
                    }

                    Label { text: "Model archive source:" }
                    TextField {
                        id: voiceModelSource
                        text: "auto"
                        placeholderText: "auto or /path/to/models"
                        enabled: voiceEnabled.checked
                        Layout.fillWidth: true
                    }

                    Label { text: "Model usage:" }
                    ComboBox {
                        id: voiceModelMode
                        model: ["Use external model archive", "Copy to installed system"]
                        enabled: voiceEnabled.checked
                    }

                    Label { text: "Local model root:" }
                    TextField {
                        id: voiceModelRoot
                        text: "/var/lib/synapse/voice-ai/models"
                        enabled: voiceEnabled.checked && voiceModelMode.currentIndex === 1
                        Layout.fillWidth: true
                    }

                    Label { text: "LLM endpoint:" }
                    TextField {
                        id: voiceLlmEndpoint
                        text: "http://192.168.5.157:8000/v1"
                        enabled: voiceEnabled.checked
                        Layout.fillWidth: true
                    }

                    Label { text: "Default language:" }
                    ComboBox {
                        id: voiceLanguage
                        model: ["it", "en", "fr", "de", "es", "pt"]
                        enabled: voiceEnabled.checked
                    }

                    Label { text: "API exposure:" }
                    ComboBox {
                        id: voiceBindMode
                        model: ["Local (127.0.0.1)", "Remote (0.0.0.0)"]
                        enabled: voiceEnabled.checked
                    }

                    Label { text: "Voice API port:" }
                    SpinBox {
                        id: voicePort
                        from: 1024
                        to: 65535
                        value: 8090
                        enabled: voiceEnabled.checked
                    }

                    Label {
                        Layout.fillWidth: true
                        wrapMode: Text.WordWrap
                        text: "Voice samples are enrolled after first login and remain private in the user's local data directory."
                    }
                }
            }

            // ── TRELLIS.2 Section ─────────────────────────────
            GroupBox {
                title: "AI / ROCm — TRELLIS.2"
                Layout.fillWidth: true
                visible: hasTrellis

                ColumnLayout {
                    spacing: 8

                    CheckBox {
                        id: trellisEnabled
                        text: "Install TRELLIS.2 ROCm image-to-3D"
                        checked: false
                    }

                    CheckBox {
                        id: trellisDownloadModels
                        text: "Download model weights during installation"
                        checked: true
                        enabled: trellisEnabled.checked
                    }

                    Label { text: "Model cache root:" }
                    TextField {
                        id: trellisModelRoot
                        text: "/var/lib/synapse/trellis2/models"
                        enabled: trellisEnabled.checked
                        Layout.fillWidth: true
                    }

                    Label { text: "Default quality profile:" }
                    ComboBox {
                        id: trellisPipelineType
                        model: ["512", "1024_cascade"]
                        enabled: trellisEnabled.checked
                    }

                    Label {
                        Layout.fillWidth: true
                        wrapMode: Text.WordWrap
                        text: "Model URLs remain editable in /etc/synapse/trellis2-rocm/models.conf for local mirrors or gated upstream models."
                    }
                }
            }
        }
    }
}
